Update the Makefile for C# to also find paths for macOS

diff --git a/csharp/Makefile b/csharp/Makefile
--- a/csharp/Makefile
+++ b/csharp/Makefile
@@ -1,8 +1,17 @@
-.PHONY: all msg clean fullclean
+.PHONY: all msg clean fullclean check-config
 
 MONO_VERSION ?= 4.5
 
-all: msg main
+ifeq ($(shell uname -s), Darwin)
+    MONO_ETC := $(shell dirname $(shell dirname $(shell realpath $(shell which mono))))/etc/mono
+else
+    MONO_ETC := /etc/mono
+endif
+
+MACHINE_CONFIG := $(MONO_ETC)/$(MONO_VERSION)/machine.config
+CONFIG_FILE := $(MONO_ETC)/config
+
+all: msg check-config main
 
 msg:
 	@echo '--- C# ---'
@@ -11,7 +20,7 @@ main.exe: main.cs
 	mcs -unsafe -out:$@ $<
 
 main: main.exe
-	mkbundle -o $@ --deps --simple --static --i18n none --machine-config /etc/mono/$(MONO_VERSION)/machine.config --config /etc/mono/config $<
+	mkbundle -o $@ --deps --simple --static --i18n none --machine-config $(MACHINE_CONFIG) --config $(CONFIG_FILE) $<
 	rm -f main.exe
 
 run: msg main
@@ -19,3 +28,13 @@ run: msg main
 
 clean:
 	rm -f main main.exe temp.* *crash*.json
+
+check-config:
+	@if [ ! -f $(MACHINE_CONFIG) ]; then \
+		echo "ERROR: The file $(MACHINE_CONFIG) does not exist."; \
+		exit 1; \
+	fi
+	@if [ ! -f $(CONFIG_FILE) ]; then \
+		echo "ERROR: The file $(CONFIG_FILE) does not exist."; \
+		exit 1; \
+	fi
